### ISSUE TITLE
Deprecate? 

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/CurlCaBundle#4]
New "more official" package https://github.com/composer/ca-bundle has been created.

Should this package be deprecated?

**Comment by mhujer** [comment]
I suggest waiting until there is an update of certificates, to see if the package from composer is updated properly.

**Comment by fprochazka** [comment]
Well, I'm definitely not gonna kill this cron right away. Also, somebody should ask them if they do have a cron ready (I'm lazy).
